# You can override the included template(s) by including variable overrides
# SAST customization: https://docs.gitlab.com/ee/user/application_security/sast/#customizing-the-sast-settings
# Secret Detection customization: https://docs.gitlab.com/ee/user/application_security/secret_detection/#customizing-settings
# Dependency Scanning customization: https://docs.gitlab.com/ee/user/application_security/dependency_scanning/#customizing-the-dependency-scanning-settings
# Note that environment variables can be set in several places
# See https://docs.gitlab.com/ee/ci/variables/#cicd-variable-precedence
image: openjdk:11-jdk

include:
  - template: Dependency-Scanning.gitlab-ci.yml
  - template: Security/Secret-Detection.gitlab-ci.yml

stages:
- compile
- test
- package
- build
- deploy
- review
- dast
- staging
- canary
- production
- incremental rollout 10%
- incremental rollout 25%
- incremental rollout 50%
- incremental rollout 100%
- performance
- cleanup
before_script:
- export GRADLE_USER_HOME=`pwd`/.gradle
- chmod +x ./gradlew
cache:
  paths:
  - ".gradle/wrapper"
  - ".gradle/caches"
compile:
  stage: compile
  script:
  - "./gradlew assemble"
test:
  stage: test
  script:
  - "./gradlew test --stacktrace"
code_style:
  stage: test
  script:
  - "./gradlew lintKotlin"
  artifacts:
    paths:
    - build/ktlint.xml
    expire_in: 1 day
  allow_failure: true
package:
  stage: package
  script:
  - "./gradlew shadowJar"
  artifacts:
    paths:
    - build/libs/*.jar
    expire_in: 1 day
sast:
  stage: test
include:
- template: Auto-DevOps.gitlab-ci.yml
