image: openjdk:11

include:
  - template: Dependency-Scanning.gitlab-ci.yml
  - template: Security/Secret-Detection.gitlab-ci.yml

stages:
- compile
- test
- package
- build
- deploy
- review
- dast
- staging
- canary
- production
- incremental rollout 10%
- incremental rollout 25%
- incremental rollout 50%
- incremental rollout 100%
- performance
- cleanup

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle

cache:
  paths:
    - ".gradle/wrapper"
    - ".gradle/caches"

compile:
  stage: compile
  script:
    - "./gradlew assemble"

test:
  stage: test
  image: openjdk:11
  script:
    - "./gradlew test --stacktrace"

code_style:
  stage: test
  script:
  - "./gradlew lintKotlin"
  artifacts:
    paths:
    - build/ktlint.xml
    expire_in: 1 day
  allow_failure: true

package:
  stage: package
  script:
    - "./gradlew shadowJar"
  artifacts:
    paths:
      - build/libs/*.jar
    expire_in: 1 day

sast:
  stage: test

include:
  - template: Auto-DevOps.gitlab-ci.yml
